//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int coment_id { get; set; }
        public string descricao_coment { get; set; }
        public Nullable<System.DateTime> dt_coment { get; set; }
        public int id_user { get; set; }
        public int id_post { get; set; }
    
        public virtual Postagem Postagem { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
