//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.Usuario1 = new HashSet<Usuario>();
        }
    
        public int grupo_id { get; set; }
        public string grupo_nome { get; set; }
        public int criador_grupo { get; set; }
        public Nullable<System.DateTime> dt_criacao { get; set; }
        public int gp_tipo { get; set; }
        public byte[] icone { get; set; }
        public string gp_descricao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Tipo_grupo Tipo_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
    }
}
