//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_premium
    {
        public int id_user { get; set; }
        public string nome_cartao { get; set; }
        public int numero_cartao { get; set; }
        public string senha_cartao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
